# docker
alias dk='docker'
alias dkv='docker volume'
alias dkvc='docker volume create'
alias dkvi='docker volume inspect'
alias dkvl='docker volume ls'
alias dkvp='docker volume prune'
alias dkvr='docker volume rm'
alias dkn='docker network'
alias dknc='docker network create'
alias dkni='docker network inspect'
alias dknl='docker network ls'
alias dknp='docker network prune'
alias dknr='docker network rm'

# docker-compose
alias dc='docker-compose'
alias dcb='docker-compose build --no-cache'
alias dcc='docker-compose config'
alias dcd='docker-compose down'
alias dce='docker-compose exec'
alias dcr='docker-compose run --rm'
alias dcu='docker-compose up -d'
alias dcps='docker-compose ps'
